apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
    tier: front
  name: vote-preview
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30100
  selector:
    app: vote
  type: NodePort
